In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [3]:
df = pd.read_csv("diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [5]:
#Chechking missing values
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
X = df.drop("Outcome", axis=1)
y = df["Outcome"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
X_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
60,2,84,0,0,0,0.0,0.304,21
618,9,112,82,24,0,28.2,1.282,50
346,1,139,46,19,83,28.7,0.654,22
294,0,161,50,0,0,21.9,0.254,65
231,6,134,80,37,370,46.2,0.238,46
...,...,...,...,...,...,...,...,...
71,5,139,64,35,140,28.6,0.411,26
106,1,96,122,0,0,22.4,0.207,27
270,10,101,86,37,0,45.6,1.136,38
435,0,141,0,0,0,42.4,0.205,29
102,0,125,96,0,0,22.5,0.262,21

In [8]:
X_test

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
668,6,98,58,33,190,34.0,0.430,43
324,2,112,75,32,0,35.7,0.148,21
624,2,108,64,0,0,30.8,0.158,21
690,8,107,80,0,0,24.6,0.856,34
473,7,136,90,0,0,29.9,0.210,50
...,...,...,...,...,...,...,...,...
355,9,165,88,0,0,30.4,0.302,49
534,1,77,56,30,56,33.3,1.251,24
344,8,95,72,0,0,36.8,0.485,57
296,2,146,70,38,360,28.0,0.337,29
462,8,74,70,40,49,35.3,0.705,39

In [9]:
X_train = X_train.replace(0, np.nan)
X_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
60,2.0,84.0,NaN,NaN,NaN,NaN,0.304,21
618,9.0,112.0,82.0,24.0,NaN,28.2,1.282,50
346,1.0,139.0,46.0,19.0,83.0,28.7,0.654,22
294,NaN,161.0,50.0,NaN,NaN,21.9,0.254,65
231,6.0,134.0,80.0,37.0,370.0,46.2,0.238,46
...,...,...,...,...,...,...,...,...
71,5.0,139.0,64.0,35.0,140.0,28.6,0.411,26
106,1.0,96.0,122.0,NaN,NaN,22.4,0.207,27
270,10.0,101.0,86.0,37.0,NaN,45.6,1.136,38
435,NaN,141.0,NaN,NaN,NaN,42.4,0.205,29
102,NaN,125.0,96.0,NaN,NaN,22.5,0.262,21

In [32]:
from sklearn.impute import SimpleImputer
blood_pressure_imputer = SimpleImputer(strategy="mean" )
X_train["BloodPressure"] = blood_pressure_imputer.fit_transform(X_train[["BloodPressure"]])
X_test["BloodPressure"] = blood_pressure_imputer.fit_transform(X_test[["BloodPressure"]])
X_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
60,2.0,84.0,72.238983,NaN,NaN,32.0,0.304,21
618,9.0,112.0,82.000000,24.0,NaN,28.2,1.282,50
346,1.0,139.0,46.000000,19.0,83.0,28.7,0.654,22
294,NaN,161.0,50.000000,NaN,NaN,21.9,0.254,65
231,6.0,134.0,80.000000,37.0,370.0,46.2,0.238,46
...,...,...,...,...,...,...,...,...
71,5.0,139.0,64.000000,35.0,140.0,28.6,0.411,26
106,1.0,96.0,122.000000,NaN,NaN,22.4,0.207,27
270,10.0,101.0,86.000000,37.0,NaN,45.6,1.136,38
435,NaN,141.0,72.238983,NaN,NaN,42.4,0.205,29
102,NaN,125.0,96.000000,NaN,NaN,22.5,0.262,21

In [11]:
X_train.isnull().sum()

Pregnancies                  91
Glucose                       5
BloodPressure                 0
SkinThickness               176
Insulin                     290
BMI                           7
DiabetesPedigreeFunction      0
Age                           0
dtype: int64

In [31]:
X_train['Glucose'] = X_train['Glucose'].replace(0, np.nan)
glucose_imputer = SimpleImputer(strategy='median')
glucose_imputer.fit(X_train[['Glucose']])
X_train['Glucose'] = glucose_imputer.transform(X_train[['Glucose']])
X_test['Glucose'] = glucose_imputer.transform(X_test[['Glucose']])
X_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
60,2.0,84.0,72.238983,NaN,NaN,32.0,0.304,21
618,9.0,112.0,82.000000,24.0,NaN,28.2,1.282,50
346,1.0,139.0,46.000000,19.0,83.0,28.7,0.654,22
294,NaN,161.0,50.000000,NaN,NaN,21.9,0.254,65
231,6.0,134.0,80.000000,37.0,370.0,46.2,0.238,46
...,...,...,...,...,...,...,...,...
71,5.0,139.0,64.000000,35.0,140.0,28.6,0.411,26
106,1.0,96.0,122.000000,NaN,NaN,22.4,0.207,27
270,10.0,101.0,86.000000,37.0,NaN,45.6,1.136,38
435,NaN,141.0,72.238983,NaN,NaN,42.4,0.205,29
102,NaN,125.0,96.000000,NaN,NaN,22.5,0.262,21

In [30]:
X_train['BMI'] = X_train['BMI'].replace(0, np.nan)
BMI_imputer = SimpleImputer(strategy='median')
BMI_imputer.fit(X_train[['BMI']])
X_train['BMI'] = BMI_imputer.transform(X_train[['BMI']])
X_test['BMI'] = BMI_imputer.transform(X_test[['BMI']])
X_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
60,2.0,84.0,72.238983,NaN,NaN,32.0,0.304,21
618,9.0,112.0,82.000000,24.0,NaN,28.2,1.282,50
346,1.0,139.0,46.000000,19.0,83.0,28.7,0.654,22
294,NaN,161.0,50.000000,NaN,NaN,21.9,0.254,65
231,6.0,134.0,80.000000,37.0,370.0,46.2,0.238,46
...,...,...,...,...,...,...,...,...
71,5.0,139.0,64.000000,35.0,140.0,28.6,0.411,26
106,1.0,96.0,122.000000,NaN,NaN,22.4,0.207,27
270,10.0,101.0,86.000000,37.0,NaN,45.6,1.136,38
435,NaN,141.0,72.238983,NaN,NaN,42.4,0.205,29
102,NaN,125.0,96.000000,NaN,NaN,22.5,0.262,21

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
# showing Age coulmn like catagorical group young(<30), Adult(30-50), Senior(>50)) and apply ordinal encoding
X_train['Age_group'] = pd.cut(X_train['Age'], bins=[0, 30, 50, np.inf], labels=['Young', 'Adult', 'Senior'])
X_test['Age_group'] = pd.cut(X_test['Age'], bins=[0, 30, 50, np.inf], labels=['Young', 'Adult', 'Senior'])

ordinal_encoder = OrdinalEncoder(categories=[['Young', 'Adult', 'Senior']])

X_train['Age_group_encoded'] = ordinal_encoder.fit_transform(X_train[['Age_group']])
X_test['Age_group_encoded'] = ordinal_encoder.transform(X_test[['Age_group']])

X_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Age_group,Age_group_encoded
60,2.0,84.0,72.238983,NaN,NaN,32.0,0.304,21,Young,0.0
618,9.0,112.0,82.000000,24.0,NaN,28.2,1.282,50,Adult,1.0
346,1.0,139.0,46.000000,19.0,83.0,28.7,0.654,22,Young,0.0
294,NaN,161.0,50.000000,NaN,NaN,21.9,0.254,65,Senior,2.0
231,6.0,134.0,80.000000,37.0,370.0,46.2,0.238,46,Adult,1.0
...,...,...,...,...,...,...,...,...,...,...
71,5.0,139.0,64.000000,35.0,140.0,28.6,0.411,26,Young,0.0
106,1.0,96.0,122.000000,NaN,NaN,22.4,0.207,27,Young,0.0
270,10.0,101.0,86.000000,37.0,NaN,45.6,1.136,38,Adult,1.0
435,NaN,141.0,72.238983,NaN,NaN,42.4,0.205,29,Young,0.0
102,NaN,125.0,96.000000,NaN,NaN,22.5,0.262,21,Young,0.0